# Generated by Django 5.0.7 on 2026-05-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='normalizedactivity',
            new_name='core_normal_tenant__28d9f8_idx',
            old_name='core_normal_tenant__2f67b7_idx',
        ),
        migrations.RenameIndex(
            model_name='normalizedactivity',
            new_name='core_normal_tenant__9c9de5_idx',
            old_name='core_normal_tenant__7057cf_idx',
        ),
    ]
